config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # A user has many posts
  # A user has many comments
  # A user has many likes
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  # Validation
  # Name must not be blank
  validates :name, presence: true

  # PostsCount must be an integer greater than or equal to zero
  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # The 3 most recent posts for a given user
  # @returns {Array<Post>}
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  # Check whether the user is an admin or not
  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<main>
  <section class='user_list'>
    <% @users.each do |user| %>
      <%= render 'shared/user', user:user%>
    <%end%>
  </section>
</main>

app/views/users/show.html.erb
<main>
  <%= render 'shared/user', user:@user%>
  <section class='user_bio'>
    <h2> Bio </h2>
    <p> <%= @user.bio %> </p>
  </section>
  <section class='recent_posts'>
    <% @user.recent_posts.each do |post| %>
      <%= render 'shared/post', post:post %>
    <% end %>
  </section>
  <section class='crud_btn'>
  <button type='button' class='all_posts_btn'>
    <%= link_to 'See All Posts', user_posts_url(@user, @posts)%>
  </button>
  <%# Create a new post %>
  <% if can? :create, Post %>
    <button type='button' class='new_post_btn'>
      <%= link_to 'Create New Post', new_user_post_url(@user) %>
    </button>
  <% end %>
  </section>
</main>