config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/views/shared/_comment.html.erb
<p>
  <%=comment.author.name%> : <%=comment.text%>
</p>
<% if can? :destroy, comment %>
  <button>
    <%= link_to 'Delete comment',user_post_comment_path(@user, comment.post, comment.id) , method: :delete, data: {
                    turbo_confirm: "Do you want to delete this comment?"
                  } %>
  </button>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |f| %>
  <div class='new_post_form'>
    <div class='field'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='field'>
      <%= f.label :text %>
      <%= f.text_area :text %>
    </div>
    <%= f.submit 'Create Post' %>
  </div>
<% end %>

app/views/shared/_form_comment.html.erb
<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>
  <div class='comment_form'>
    <div class='field'>
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>
    <%= form.submit 'Create Comment' %>
  </div>
<% end %>

app/views/shared/_form_post.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |f| %>
  <div class='post_form'>
    <div class='field'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='field'>
      <%= f.label :text %>
      <%= f.text_area :text %>
    </div>
    <%= f.submit 'Create Post' %>
  </div>
<% end %>

app/views/shared/_post.html.erb
<section class='post_card'>
  <h2> <%= link_to post.title, user_post_path(@user,post) %> </h2>
  <%# Truncate the text in a post if the length is greater than 40 %>
  <% max_length = 40 %>
  <% if post.text.length > max_length %>
    <% post.text = post.text.slice(0,max_length) + "..." %>
  <% end %>
  <p> <%= post.text %> </p>
  <section class='post_card__stat'>
    <p> Comments: <%= post.comments_count %> </p>
    <p> Likes: <%= post.likes_count %> </p>
  </section>
</section>

app/views/shared/_user.html.erb
<section class='user_card'>
  <div class='user_card__image'>
    <img src= <%= user.photo %>/>
  </div>
  <div class='user_card__info'>
    <h2><%= link_to user.name, user %></h2>
    <p>Number of posts: <%= user.posts_count %></p>
  </div>
</section>