config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  # A post belongs to an author
  # A post has many comments
  # A post has many likes
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Validation
  # Title must not be blank
  validates :title, presence: true

  # Title must not exceed 250 characters
  validates :title, length: { maximum: 250 }

  # CommentsCounter must be an integer greater than or equal to zero
  validates :comments_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # LikesCounter must be an integer greater than or equal to zero
  validates :likes_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # The 5 most recent comments for a given post
  # @returns {Array<Comment>}
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  # Update the posts counter every time a new post
  # is created for a given user
  after_save :update_posts_count

  # Updates the posts counter for a user
  # @returns {Integer} the number of posts for a given user
  private

  def update_posts_count
    author.increment!(:posts_count)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  # GET /users/:user_id/posts
  def index
    @user = User.find(params[:user_id])
    # retrieve posts associated to @user and
    # eager-loading the associated comments
    @posts = @user.posts.includes(comments: [:author])

    # api endpoint to list all posts for a user
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  rescue ActiveRecord::RecordNotFound
    # Handle the case where the user is not found
    # Redirect to the root page
    flash[:error] = 'User not found.'
    redirect_to root_path
  end

  # GET /users/:user_id/posts/:id
  def show
    @user = User.find(params[:user_id])
    # retrieve the post associated to @user and
    # eager-loading the associated comments
    @post = @user.posts.includes(:comments).find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    # create a new post associated to the current_user
    @post = current_user.posts.create(post_params)
    @post.author = current_user

    if @post.save
      # if post saved, redirect to the user's posts and render success message
      redirect_to user_posts_path(current_user), notice: 'Post created successfully.'
    else
      # if post not saved, render new template and render error message
      render :new, notice: 'Post could not be created.'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])

    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy

    redirect_to user_posts_path(@user)
  end

  private

  # Whitelist and extract the allowed parameters
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<main>
  <%= render 'shared/user', user:@user%>
  <section class='post_list'>
    <% @posts.each do |post| %>
      <section class='post_item'>
        <%= render 'shared/post', post:post%>
        <% unless post.recent_comments.empty? %>
          <h4>Comments</h4>
          <section class='comment_list'>
            <% post.recent_comments.each do |comment| %>
              <%= render 'shared/comment', comment:comment%>
            <% end %>
          </section>
        <% end %>
      </section>
    <% end %>
  </section>
  <section class='crud_btn'>
    <button type='button' class='pagination'>Pagination</button>
    <%# Create a new post %>
    <% if can? :create, Post %>
      <button type='button' class='new_post_btn'>
        <%= link_to 'Create New Post', new_user_post_url(@user) %>
      </button>
    <% end %>
  </section>
</main>

app/views/posts/new.html.erb
<main>
  <h1> Create a new post </h1>
  <%= render 'shared/form_post' %>
</main>

app/views/posts/show.html.erb
<main>
  <article class='post'>
    <h2> <%= @post.title %> by <%= link_to @user.name, @user %></h2>
    <section class='post_card__stat'>
      <p> Comments: <%= @post.comments_count %> </p>
      <p> Likes: <%= @post.likes_count %> </p>
    </section>
    <p class='post_body'> <%= @post.text %> </p>
    <% unless @post.comments.empty? %>
      <h4> Comments </h4>
      <section class='comment_list'>
        <% @post.comments.each do |comment| %>
          <%= render 'shared/comment', comment:comment %>
        <% end %>
      </section>
    <% end %>
  </article>
  <section class='crud_btn'>
    <button type='button'>
      <%= link_to 'Add New Comment', new_user_post_comment_path(@post.author, @post) %>
    </button>
    <section class='like_form'>
      <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |f| %>
        <%= f.submit 'Like 👍🏽' %>
      <% end %>
    </section>
    <% if can? :destroy, @post %>
      <%= button_to 'Delete post', user_post_path(@user, @post), method: :delete %>
    <% end %>
  </section>
</main>